In [ ]:
#imports various libraries
import pandas as pd
pd.set_option('display.max_colwidth', -1)
import numpy as np
import pickle
from tqdm import tqdm

from collections import Counter
from nltk import ngrams
import re
import copy 
import matplotlib.pyplot as plt

# Analysing All URLs

In [138]:

with open('../../Ignore/SCMP_All_URLs.pkl', 'rb') as f:
    df = pickle.load(f)
    
df

,urls,date
0,https://www.scmp.com/news/world/united-states-canada/article/3109887/after-assailing-fox-news-calling-arizona-bidens,2020-11-14 15:39:00+00:00
1,https://www.scmp.com/news/world/europe/article/3109886/coronavirus-europe-further-tightens-curbs-stem-second-wave-global,2020-11-14 14:30:00+00:00
2,https://www.scmp.com/comment/opinion/article/3109884/instilling-patriotism-young-needs-more-rituals-and-indoctrination,2020-11-14 13:24:00+00:00
3,https://www.scmp.com/comment/opinion/article/3109883/ending-hong-kong-sanctions-would-be-good-start-biden,2020-11-14 13:24:00+00:00
4,https://www.scmp.com/sport/racing/article/3109882/forte-justifies-expensive-price-tag-impressive-debut-win-sha-tin,2020-11-14 14:11:00+00:00
...,...,...
1458116,https://www.scmp.com/tech/policy/article/3099673/white-house-will-crack-down-more-chinese-apps-after-tiktok-wechat-trump,2020-09-05 08:23:00+00:00
1458150,https://www.scmp.com/news/world/united-states-canada/article/3099635/coronavirus-us-cases-top-6-million-johns-hopkins,2020-08-31 22:49:00+00:00
1458151,https://www.scmp.com/week-asia/politics/article/3099634/us-india-dialogue-october-china-and-defence-cooperation-will-be,2020-08-31 23:49:00+00:00
1458170,https://www.scmp.com/economy/china-economy/article/3099575/us-china-style-trade-wars-could-proliferate-without-wto,2020-09-02 01:14:00+00:00
1458193,https://www.scmp.com/comment/opinion/article/3099420/how-us-china-tensions-are-pushing-us-listed-chinese-tech-firms-hong,2020-09-01 04:43:00+00:00

In [139]:
links_text = ' '.join(list(df.urls))
links_text = links_text.replace("https://www.scmp.com", " ")
links_text = links_text.replace("/", " ")

ngram_counts = Counter(ngrams(links_text.split(), 1))

In [140]:
ngram_counts.most_common(10)

[(('article',), 1166800),
 (('news',), 176934),
 (('hong-kong',), 63334),
 (('world',), 50692),
 (('china',), 45359),
 (('business',), 43732),
 (('sport',), 40380),
 (('magazines',), 37193),
 (('comment',), 32690),
 (('asia',), 28991)]

In [141]:
#just got the tags manually
contain_china = []
contain_hk = []

for link in df.urls:
    #contain_china
    if '/china/' in link or '/china-digest/' in link or '/china-insider/' in link or '/hong-kong-china/' in link :
        contain_china.append(1)
    else:
        contain_china.append(0)

    #contain_hk
    if '/hong-kong/' in link or '/hong-kong-china/' in link:
        contain_hk.append(1)
    else:
        contain_hk.append(0)

df['China_tag'] = contain_china
df['HK_tag'] = contain_hk

tag_df = df.loc[:, df.columns.intersection(['China_tag','HK_tag'] )]

tag_df = tag_df.groupby(df.date.dt.year).agg(['sum'])
tag_df["ratio"] = tag_df[('China_tag', 'sum')] /  tag_df[('HK_tag', 'sum')]
# tag_df

# Load Complete News Dataset

In [142]:
#load dataset from scrap notebook
with open('../Pickles/SCMP_News_Full.pkl', 'rb') as f:
    df = pickle.load(f)
    
#for getting china articles
china_df = copy.deepcopy(df)

df.tail()

,Title,Author,Summary,Topic,Link,Date
92246,"Hong Kong police inspector arrested on suspicion of stealing colleagues’ tactical helmets, abalone",Christy Leung,The disappearance of the tactical gear and canned seafood from the offices of the public relations bureau prompted the man’s colleagues to file a complaint.,"Hong Kong police,Crime in Hong Kong",https://www.scmp.com/news/hong-kong/law-and-crime/article/3109872/hong-kong-police-inspector-arrested-suspicion-stealing,2020-11-14 15:28:00+00:00
92247,"Mandatory Covid-19 testing for ‘high-risk’ groups in Hong Kong gets nod, those who ignore orders face jail, fines","Elizabeth Cheung,Gigi Choy,Chris Lau",Other new measures include reintroduction of four-person cap on tables at eateries.,"Coronavirus pandemic,Coronavirus pandemic: All stories,Coronavirus Hong Kong,Hong Kong social distancing,Executive Council of Hong Kong",https://www.scmp.com/news/hong-kong/health-environment/article/3109853/coronavirus-hong-kongs-executive-council-signs,2020-11-14 15:30:00+00:00
92248,Pope Francis said to be in final stage of selecting new Hong Kong bishop,Mimi Lau,"Pontiff has three nominations to consider after an earlier announcement was postponed, according to informed source.","China-Vatican relations,Catholic Church,Hong Kong national security law (NSL),Pope Francis",https://www.scmp.com/news/china/diplomacy/article/3109825/pope-francis-said-be-final-stage-selecting-new-hong-kong,2020-11-14 15:30:00+00:00
92249,"Hong Kong’s controversial national security law tip line gets 10,000 messages in first week of operation",Christy Leung,"By 8am on Thursday, the multi-platform project had gathered the equivalent of 1,400 piece of information a day for the force’s new national security unit.","Hong Kong national security law (NSL),Hong Kong police,Hong Kong protests",https://www.scmp.com/news/hong-kong/law-and-crime/article/3109867/hong-kongs-controversial-national-security-law-tip,2020-11-14 15:47:00+00:00
92250,"Mandatory Covid-19 testing for ‘high-risk’ groups in Hong Kong gets nod, those who ignore orders face jail, fines","Elizabeth Cheung,Gigi Choy,Chris Lau",Other new measures include reintroduction of four-person cap on tables at eateries.,"Coronavirus pandemic,Coronavirus pandemic: All stories,Coronavirus Hong Kong,Hong Kong social distancing,Executive Council of Hong Kong",https://www.scmp.com/news/hong-kong/health-environment/article/3109853/coronavirus-hong-kongs-executive-council-signs,2020-11-14 16:03:00+00:00

# News Articles By Date

In [128]:
years = df.groupby(df.Date.dt.year).agg(['count'])
years[(   'Date', 'count')]

Date
2012    2894
2013    10730
2014    9089
2015    10150
2016    12260
2017    12407
2018    13926
2019    11245
2020    9550
Name: (Date, count), dtype: int64

In [129]:
months = df.groupby([df.Date.dt.year, df.Date.dt.month]).agg(['count'])
#dict(months[(   'Date', 'count')])

# Get Author List

In [145]:
pass_20_articles = []
for i in list(df.Author):
    if list(df.Author).count(i) > 20:
        pass_20_articles.append(i)

KeyboardInterrupt:

In [ ]:
pass_20_articles

In [136]:
authors_text = ', '.join(list(df.Author))
# excluse authors with less than 30 articles
unique_authors = list(set(authors_text.split(",")))
unique_authors

[' Global Post',
 ' Owen Churchill',
 ' Ruth Benny',
 'Phoebe Zhang',
 'SCMP Reporters',
 ' Note from the Editor-in-Chief',
 ' Hana Davis',
 'Lee Jeong-ho',
 ' DR KAREN LEE',
 ' Luisa Tam',
 ' KRISTINE KOWK',
 ' The New York Times in Baghdad',
 ' James Donally',
 ' Kimmy Chung',
 ' The New York Times in Boynton Beach',
 ' Catherine Chan',
 'Susan Ramsay',
 'Olga Wong',
 ' EMILY',
 'Jodi Xu Klein',
 ' JENIFER NGO',
 ' EUGENE LOW',
 'FRANK FENG',
 ' Guo Rui',
 'Bong Xin Ying',
 'Cedric Sam',
 ' Rana Mitter',
 ' TOMY CHEUNG',
 ' Simon Ng',
 ' Rachel Yeo',
 ' PASTY MOY',
 ' Ben Pang',
 'Chen Yifei',
 ' Leonie Kijewski',
 'Suzanne Sataline',
 ' Education Post',
 ' and Baghdad',
 'Xie Yu',
 ' Alun John',
 ' Ernest Kaov',
 ' TONY  CHEUNG',
 ' Tim Wenniges',
 'Sarah Zheng',
 'Alice Shen',
 ' HELEN YU',
 ' Melanie Leung',
 'Anita Lam',
 ' Bien Perez',
 ' Enoch Li',
 ' Yvonne Liu',
 ' Aegis Advisors Limited',
 'Marcelo Duhalde',
 ' Simon T.M. Ng',
 'Colleen Lee',
 ' KEIRA LU',
 ' Tracy Zhang',
 'Kwong Man-ki in Beijing',
 'Simone McCarthy',
 ' Langi Chiang',
 ' CITY DIGEST',
 ' Glen Norris',
 'Denise Tsang',
 ' Adlofo Arranz',
 ' Bryane Michael',
 '20',
 ' Sam Agars',
 ' Amy Li <a href=',
 ' Angela Meng',
 ' Adam Wright',
 ' Jessica Stone',
 ' Los Angeles Times in Shanghai',
 'Jane Li',
 ' Celia Chen',
 ' Teresa Li',
 ' Derek Scissors',
 ' Francesco Sisci',
 ' Agence France Presse in Montreal',
 ' Jing Zhang',
 ' Stephen Chen',
 'Rhea Mogul',
 ' Michael Barris',
 ' Jennifer Ngo',
 ' CHIFAI.CHEUNG',
 ' NICK EDWARDS',
 ' Joyce Man',
 ' Tamara Thiessen',
 ' The New York Times in Riverside',
 ' HE HEIFENG',
 ' SHIRLEY',
 'Cary Huang',
 ' Chris White',
 'Ben Westcott',
 ' Mike Rowse',
 ' Irene Pyne',
 'Verna Yu',
 'Kimmy Chung',
 ' Aileen Thomson',
 'ng kang-chang',
 ' Sue-Ann Chia',
 ' Kevin Kwong',
 ' JULIAN',
 ' Michelle Wong',
 ' Tonderayi Mukeredzi',
 'Liu Zhen',
 ' PATRICK BOEHLER DANIEL REN',
 'Fanny W. Y. Fung. Emily Tsang',
 'TO HAN SHIH',
 ' STUART LEE',
 'Pearl Lee',
 'Lauren James',
 ' Fiona Sun',
 'AMY',
 ' James Wilkinson',
 ' Agence France-Press in Sydney',
 ' Shea Driscoll',
 ' Simone McCarthy',
 ' BYRAN HARRIS',
 ' Rachel Jacqueline',
 'Choi Chi-yuk',
 'and Elizabeth Cheung',
 ' Paul Zach',
 ' Professor Simon N. M. Young',
 ' Steve Dunthorne',
 ' Andrew McNicol',
 'JOYCE  NG',
 ' Naomi Ng',
 ' Agence France Press in Beirut',
 ' Xu Donghuan',
 'Today Online',
 ' Ho Hei-wah',
 ' Satish Cheney',
 ' Fiona Tam',
 ' HANNAH XU',
 ' Ivanka Lou',
 'William Zheng',
 ' Brahma Chellaney',
 'Lilian Cheng',
 'Cissy Zhou',
 ' SANDY',
 ' Restidia Putri',
 ' Febriana Firdaus',
 ' Jiang Sijia',
 'Jeff Chen',
 ' CHEUNG CHIFAI',
 'Iris Deng',
 'Wang Feng',
 ' Bernice Chan',
 ' The Street',
 ' Natalie Mu',
 ' KEIRA HUANG LU',
 ' Deepu Sebastian Edmond',
 'TONY LEUNG',
 'Shi Jiangtao',
 ' Guy Haydon',
 ' Kathy Gao',
 ' Andrew Salmon',
 ' Phila Siu',
 ' Dennis Chong',
 ' Denise Cheung',
 ' Sarah Engstrand',
 ' Gloria Chan',
 'Orange Wang',
 ' Kwong Man-ki in Beijing',
 ' PROD',
 'Elizabeth Cheung',
 ' May Chan Rhodes',
 ' Jeanny Yu',
 ' Allen Au-yueng',
 ' Benjamin Robertson',
 ' LA TIMES',
 ' Tim Noonan',
 'Robin Fall',
 ' Sean Kennedy',
 ' M Joseph',
 ' Zhang Hong',
 ' OSCAR HO',
 ' MANY ZUO',
 ' Raquel Carvalho',
 'SUZANNE VAN DER ERF',
 'Jeffie Lam in Beijing',
 'Linda Yeung',
 ' Shaheera Abdullah',
 ' Teddy Ng',
 'Elizabeth Chueng',
 ' Sanya Tourism',
 ' PHOENIX KWONG MAN-KI',
 ' Linda Yeung',
 ' Agence France Presse in London',
 ' Yonden Lhatoo',
 'Jonathan White',
 ' Logan Pauley',
 ' Peter Mathieson',
 ' Ng Tze Wei',
 ' Billy SK Wong',
 ' Jevans Nyabiage',
 'JOLIE HO',
 'CALVIN LIU',
 ' EMIILY TSANG',
 ' Meaghan Tobin',
 ' Bibek Bhandari',
 ' Tammy Tam',
 ' FANNY WY FUNG',
 'John R. Carter',
 'Rolien Hoyng',
 ' Allen Au-yeung',
 'Tom Wang',
 ' Cai Xinglun',
 ' FRANK FENG',
 'Maggie Zhang',
 ' AUSTIN',
 ' AUSTIN CHIUI',
 ' Xenia Chan',
 'Adam Behsudi',
 'E MILY TSANG',
 ' Caroline Drewett',
 ' Lauren Chan',
 ' James Griffiths',
 'FANNY KY FUNG',
 ' Tanna Chong',
 ' The New York Times in Athens',
 ' David Eimer',
 ' Kristin Huang',
 ' Jason Y Ng',
 ' Luke Tsang Chee-wah',
 ' CHOI CHIYUK',
 ' JOYVE NG',
 ' Gigi Choy',
 'Xinyan Yu',
 'Frank Tang',
 'Stephanie Tsui',
 ' Raymond Li',
 ' JOYCE',
 'Mischa Moselle',
 ' PAUL W T SHIEH',
 ' Mario Calabresi',
 'Teddy Ng',
 ' EMILY.TSANG',
 ' ZHUANG',
 ' Ethan Paul',
 ' Godfrey Olukya',
 'Kunal Purohit',
 'Mimosa Ngai',
 'The Star',
 ' Victor Ting',
 ' Pearl Liu',
 'Viola Zhou',
 ' Maseeh Rahman',
 'Sarah Owermohle',
 ' JENNFER NGO',
 'Jasmine Siu',
 ' Susan Finder',
 ' Agence France Press in Seoul',
 ' Alex Shi',
 'Stephy Shi Yuhan',
 ' Daniel Bases',
 ' Rene Pastor',
 ' Danil Bochkov',
 ' Francine Chen',
 ' Rachel Leung',
 ' Cheryl Heng',
 'JI LING',
 'Kristine Kwok',
 'Karen Zhang',
 ' CHEUNG CHI-FAIR',
 ' Jolene Otremba',
 ' Resty Woro Yuniar',
 ' Dongyao Nie',
 ' Michael Chugani',
 ' AGENICIES',
 ' Stephen Quinn',
 ' Fanny W.Y.Fung',
 ' Lilian Cheng',
 'Phoenix Kwong',
 ' Vivienne Chow',
 ' Violet Law',
 ' Murtaza Solangi',
 ' John Brennan',
 ' LOUISE HO',
 ' John R. Carter',
 ' CHOI CHOI-YUK',
 ' Shawn Yuan',
 ' CARY HUANG IN BEIJING',
 ' Patrick Boehler <a href=',
 ' Josephine Ma',
 ' MARA HVISTENDAHL',
 ' Hong Tran',
 ' Tony Cheung in Chicago',
 ' CHIM SAU-WAI',
 'Jing Li',
 ' KATHLEEN NUTT',
 ' CANCY CHAN',
 ' TRIBUNE',
 'JOSHUA BUT',
 ' Nicolas Groffman',
 ' Natalie Wong',
 ' Tamar Herman',
 ' FANNY W.Y. FUNG',
 ' ANGELA MENGG',
 'Natalie Wong',
 ' SCAD',
 ' Christopher DeWolf',
 'Zhou Jiaquan',
 ' AUSTIN CHU',
 ' Abigail Collier',
 'Kevin Kwong',
 'Alvin Lum',
 ' John Carney',
 'Andre Barahamin',
 ' Peggy Sito',
 ' Agence France Press in Madrid',
 ' FANNY FUND',
 ' The New York Times',
 'Raissa Robles',
 'Georgina Lee',
 'Laura Ma',
 'Chris Lau',
 ' Chieu Luu',
 'James Wilkinson',
 'Xenia Chan',
 ' AUSTIN.CHIU',
 'Sophie Yu',
 ' Edward Howell',
 ' Kate Whitehead',
 ' Marco Hernandez',
 ' Eric Cheung',
 ' FANNY WF FUNG',
 ' MICHAEL DEWAALMONTGOMERY',
 ' Adrian Wan',
 ' Emily Allen',
 ' LAM WOON KWONG',
 ' Simpson Cheung',
 ' Mandy Zuo',
 ' Jessica Simpsons',
 'Toh Han Shih',
 'Compiled by Francine Chen',
 'Bryan Harris',
 'Alberto Lucas López',
 ' Karen Chiu',
 ' PHILA',
 ' Carrie Lam',
 'Olivia Rosenman',
 ' PINGHUI ZHUANG',
 ' WEN REN',
 ' Pam Walker',
 ' Zoe Low',
 'DARREN WEE',
 ' CNBC',
 ' Owen Fung',
 'Melanie Leung',
 ' THE ASSOCIATED PRESS',
 ' SHIRLEY YUEN',
 ' Zhou Jiaquan',
 'Niall Fraser',
 ' Casandra Boruzescu',
 ' GABRIELA KENNEDY',
 'Emilia Goh',
 ' Beh Lih Ti',
 ' Press Association',
 ' Michael Lipin',
 ' ZHANG  PINGHUI',
 ' Orji Sunday',
 ' Toh Han Shih',
 'Amy Li',
 ' Law Chi-kwong',
 ' Vivian Chiu Tejada',
 ' Che Pan',
 ' Sandra Lowe',
 ' ANNEMARIE  EVANS',
 ' Catherine Wong',
 ' PHILIA SIU',
 ' Raymond Cheng',
 ' Stephen Vines',
 ' Meng Jing',
 ' Nosmot Gbadamosi',
 'Raquel Carvalho',
 ' Jodi Xu Klein',
 ' Iris Deng',
 ' Bac Pham',
 ' Stuart Lau',
 ' Suen Yiu-tung',
 ' ZHUANG PINGUI',
 ' Peta Tomlinson',
 ' Staff Reporter in Kunming',
 'Kelly Ho',
 ' RAQUEL',
 'Summer Zhen',
 ' JULIA RYALL',
 'PHOENIX KWONG MAN-KI',
 'SCMP',
 ' ELLLIS LIANG',
 'Zuraidah Ibrahim',
 ' Agence France Presse in Hanoi',
 ' SIJA JIANG',
 'Harminder Singh',
 'Celine Sun',
 ' THMAS CHAN',
 ' Don Weinland',
 'Ivan Zhai',
 ' SCMP Reporters',
 ' Sophia Lam',
 'Compiled by SCMP’s Asia desk',
 ' Thomas Sturrock',
 'Thomas Yau',
 ' Shi Jiangtao',
 ' Jane Cai',
 ' The New York Times in Toronto',
 'Celine Ge',
 ' Bhavan Jaipragas',
 ' Edouard Morton',
 ' Ed Peters',
 ' Matt Hodges',
 'Nazvi Careem',
 ' Chow Chung-yan',
 ' GENE FRIEDA',
 ' Jennifer Pak',
 ' Su-Lin Tan',
 'FANNY W. Y. FUNG',
 ' Orange Wang',
 ' Lana Lam',
 ' Alvin Sallay',
 ' Lucy Christie',
 ' Mary Ann Benitez',
 'ALEC CHEUNG',
 ' Coco Feng',
 ' Erin Chan',
 'CHARMAINE CHE',
 ' Patsy Moy',
 ' Agence France Presse in Brussels',
 ' Paul Bischoff',
 'VICTORIA ANN DUTHIE',
 ' Ian Romboletti',
 'Tony Cheung',
 ' LAWRENCE CHEUNG',
 ' Agence France Press in Montreal',
 'Shirley Zhao',
 ' Asociated Press in Seoul',
 ' Vickie Chan',
 ' Liz Mak',
 ' Tom Biddington',
 ' Enoch Yiu',
 ' Amrit Dhillon',
 ' Emily Tsang',
 ' Daryl Choo',
 ' Stephen Applebaum',
 'GLORIA CHAN',
 'Julian Ryall',
 ' Lynn Lee',
 ' Stephanie Augustin',
 ' Jeanette Wang',
 ' Matt Kwok',
 'Crystal Tai',
 ' Liu Jun',
 ' Yusmadi Yusoff',
 ' Sreejith Sreedharan',
 'Naomi Ng',
 ' Jack Laurenson',
 ' JULIE CHU',
 ' Kristie Wong',
 'Alvin Sallay',
 'LAI YING-KIG',
 ' Keira Lu Huang in Washington',
 ' Shirley Yuen',
 ' ANNEMAIRE EVANS',
 ' Guy Lougher',
 ' Simeon Jupp',
 'Keith Zhai',
 'Adam Wright',
 'Inderjit Singh',
 ' Wong Yan-lung',
 'Giulio Rubino',
 ' Lee Jeong-ho',
 'Kwong Man-ki',
 'Tracy Qu',
 ' Grenville Cross',
 ' Daniel Cheng',
 ' Andrew London',
 ' Malcolm Kay',
 'Leonard So',
 'Rachel Yeo',
 ' Vasudevan Sridharan',
 'Kathleen Magramo',
 ' Agence France Presse in Paris',
 'Nicola Chan',
 ' Andre Barahamin',
 'Snow Xia',
 ' Wang Xiangwei',
 'Aron Harilela',
 'Nectar Gan',
 ' Aleksander Solum',
 ' Ralph Jennings',
 ' Choi Chi-yuk',
 'Michelle Wong',
 'Chutima Sidasathian',
 ' Cliff Buddle',
 ' Summer Zhen',
 ' CHI-FAI CHEUNG',
 ' WONG YATHEI',
 ' Sascha Matuszak',
 ' Hu Jianlong',
 ' Frank Tang',
 ' Sijia Jiang',
 'Alan Yu',
 ' Maggie Zhang',
 ' Michael Kovrig',
 ' Agence France Presse in Seoul',
 'Jeoffrey Maitem',
 ' Alice Yan',
 ' Logan Connor',
 'He Huifeng',
 ' Lawrence Chung',
 ' Luz Ding',
 ' NIALL  FRASER',
 'Laura Westbrook',
 ' Stephanie Tsui',
 'Tom Biddington',
 ' Fan Di',
 ' GLORIA CHAN',
 ' Vanessa Cheung',
 ' ALL AU-YEUNG',
 ' Howard Winn',
 'JOHNNIE TAM',
 'Thailand',
 ' TONY CHUENG',
 'PHILA',
 ' DIETER YIH',
 'Dewey Sim',
 ' Raymond Yeung',
 'Edward Tang',
 ' Mischa Moselle',
 ' Fanny Fung',
 ' Sylvia Yu',
 'Audrey Yoo',
 ' JIM MCG',
 ' ANGELA M ADRIAN W',
 ' Austin Chi',
 ' Agence France Presse in Los Angeles',
 ' Lau Ka-kuen',
 'Peter So',
 ' Christy Choi',
 ' Richard Castka',
 ' Agence France Presse in Beijing',
 'Lai Ying-kit',
 ' Agence France Press in Berlin',
 'Veta Chan',
 ' ZHUANG PENGHUI',
 ' Stephen Seawright',
 ' Michael C. Davis',
 ' Agence France=Presse in Beijing',
 ' Verna Yu',
 ' John Glynn',
 'Vicky Feng',
 ' MINNE CHAN',
 ' BEN GARVEY',
 ' Fairoza Mansor',
 ' Agence France Presse in Shanghai',
 ' Johnny KS Tam',
 'JEFFIE',
 'Amanda Lee',
 'Lea Li',
 ' JAMES',
 'Adrian Wan',
 'ANN YIP',
 ' Alice Yan. Laura Zhou',
 ' TNS',
 ' Miguel Carbonell',
 'Emily Wong',
 ' Yu Yuet',
 'Echo Xie',
 'Jeremy Blum',
 ' Alice Shen',
 ' George McKibbens',
 'JULIAN RYAL',
 'Saikou Ceesay',
 'Sue Su',
 'Selina Cheah',
 ' PEGGY SITO ENOCH YIU',
 ' Jo Baker',
 ' Jack Liu',
 'MICHAEL DE WAAL MONTGOMERY',
 ' Richard James Havis',
 ' Edmund Lim',
 ' ALICA YAN',
 ' Agence France Press in Nantes',
 ' Sarah Zheng',
 'Sue Ng',
 ' VANESSA WONG',
 'ALLEN AU YEUNG',
 ' VICTORIA KUNG',
 'Echo Hui',
 ' Nitin Pangarkar',
 'Stephen Chen',
 ' ALEC CHEUNG',
 'Chris Luo',
 ' Business Insider',
 ' PHIL SIU',
 ' Katrina Rozga',
 'CECE ZHANG',
 ' Compiled by Meaghan Tobin',
 ' STEVEN GALLAGHER',
 ' Emma Kazaryan',
 ' Ana Salvá',
 ' Jennifer Cheng',
 'Joanne Ma',
 ' Cheryl Arcibal',
 ' Mandy Zhou',
 ' Agence France Presse in Bogota',
 'Ray Chan',
 ' ANDREW RAFFELL',
 ' C C LUK',
 ' ZHUNAG PINGHUI',
 ' Wesley Morgan',
 ' Amy Li',
 'Phila Siu',
 'Laura He',
 ' JAMES GRIIFFITHS',
 ' Wendy Wu',
 ' Mimosa Ngai',
 'Benjamin Robertson',
 ' James Rose',
 ' THOAMS CHAN',
 ' John McBeth',
 ' Alice Tse',
 ' Alan Aitken',
 'Alan Robles',
 ' Andrew McCormick',
 ' Ian Young  in Vancouver',
 'Felix Wong',
 ' Paula DiPerna',
 'Karen Yeung',
 ' Laura Westbrook',
 ' Chris Luo',
 ' Inkstone',
 ' The New Zealand Herald',
 ' Supriya Batra',
 ' Jeoffrey Maitem',
 ' Jane Zhang',
 ' VIVIENNE.CHOW',
 'Lauren Chan',
 ' CHEUNG CHOR-YUNG',
 ' Graham Earnshaw',
 ' Vivian Chiu',
 'Alun John',
 ' Laurence Chu',
 'Owen Churchill',
 'Zoe Law',
 ' DPA',
 ' TANNA CHEUNG',
 ' Sidney Leng',
 'Ryan Swift',
 ' VICTORIA ANN DUTHIE',
 ' John Cremer',
 'Jason Cheng \uf025and Johnny Tam',
 'Finbarr Bermingham',
 ' Peter Simpson',
 ' The New York Times in London',
 ' Manira Chaudhary',
 ' Le Meridien Xiamen',
 'Ginn Fung',
 ' Associate Press in Beijing',
 'Pearl Liu',
 'Christy Choi',
 ' SCMP Graphics',
 'Raymond Li',
 'Sum Lok-kei',
 'MICHELLE TOH',
 ' Liu Zhen',
 'Fanny W.Y Fung',
 'Evanna Gurung',
 ' Natasha Rogai',
 ' CARY',
 ' Philip Bowring',
 ' Kyodo in Beijing',
 ' AMY  NIP',
 ' Alice Tan',
 ' Zheng Yangpeng',
 ' David Vetter',
 'Li Jing',
 ' LAM WOON-KONG',
 'Nicolo Govoni',
 ' Ada Lee',
 'Zheping Huang',
 ' CECE ZHANG',
 'Cheung Chi Fai',
 ' Agence France Press',
 ' LAURENCE CHUNG',
 ' The Los Angeles Times',
 ' Richard Harris',
 'Helene Franchineau',
 'Zhou Xin',
 'Josh Ye',
 ' Ding Duo',
 'Angela Meng',
 ' TONY',
 'Jevans Nyabiage',
 ' Chris Rowley',
 ' Andrew Barclay',
 ' KIM WALL',
 ' Donald Tsang',
 ' LILLY ZHANG',
 ' Jonathan Mok',
 ' FOREIGN POLICY',
 ' Staff photographers',
 'MIMNNIE CHAN',
 ' LAWERENCE CHUNG',
 ' ANDREA CHEN SHIRLEY ZHAO',
 ' Kalinga Seneviratne',
 'Laurence Chu',
 ' Marianne Lagutaine',
 ' Bernd Debusmann Jr',
 ' Hilary Clarke',
 ' JULIAN RYAL',
 ' PYETON GUAN',
 ' LI JING IN TIANJIN',
 ' PATSY',
 ' SIMPSON',
 ' CSM',
 ' JOHN HARDIE',
 ' Cat Schuknecht',
 ' Christopher Cheung',
 ' Victoria Ruan',
 ' Beijing',
 ' Julile Chu',
 ' Bangkok Post',
 ' RAQ',
 ' Vanessa Piao',
 ' Vincent Connor',
 ' Morning Studio editors',
 ' COLLEN LEE',
 'Cannix Yau',
 'Marco Hernandez',
 ' Linas Jegelevicius',
 ' Ryskeldi Satke',
 'Catherine Wong',
 ' David Wong',
 ' Linjin Li',
 ' Stanley Widianto',
 ' Kylie Knott',
 ' Crystal Tai',
 ' Michael Kohn in Ulan Bator',
 ' Slate',
 ' Carmen Cheung',
 'Raphael Blet',
 ' Steven Millward',
 ' clifford.lo',
 ' Samuel Chan in Bangkok',
 'Bhavan Jaipragas',
 ' SIMON CHAN',
 'Keira Huang',
 ' Chris Green',
 ' Ginn Fung',
 'Clifford Lo',
 ' JONATHAN LEVINE',
 ' Amy Yip',
 "Ben O'Rourke",
 ' SIMON YOUNG NGAI-MAN',
 ' Jeremy Blum',
 ' SCMP Editorial',
 'Greg Torode',
 ' Susan Jung',
 ' Robert Park',
 ' JULAIN RYALL',
 ' Paggie Leung',
 ' The Yomiuri Shimbun',
 'Lau Xiang Yi',
 'Kristin Huang',
 ' James Bowen',
 ' KRISTINE',
 ' Clifford Lo',
 ' Lam Woon-Kwong',
 ' Agence France-Prsse in Gao',
 ' Josh Ye',
 'Yujie Xue',
 'Lebanon',
 ' DUNCAN ABATE',
 ' Chris Helali',
 'Jessica Mary Turner',
 ' VERNA WU',
 ' Joy Chen',
 ' LAI TING-KIT',
 ' Carry Huang',
 'KANIS LI',
 ' Kate Bartlett',
 'Zhenhua Lu',
 ' Agence France Presse in Thatta',
 'Janet Sun',
 ' Danny Mok',
 'Kyodo',
 ' SUZANNE VAN DER ERF',
 ' Timmy Sung',
 'Jean Lin',
 ' CHARMAINE CHE',
 ' Johnny Tam',
 ' Eric Ng',
 ' Michael Kohn',
 'Emma Kazaryan',
 'Jeanny Yu',
 ' LIZ MAK',
 'Kylie Knott',
 ' OLIVER  CHOU',
 ' Edward Tang',
 'Karif Wat',
 ' Ed Zhang',
 ' HUI HUIFENG',
 'Joyce Ng',
 'GLORIA',
 ' Wilson Lau',
 ' C1 DIGEST',
 ' Reutes in Seattle',
 ' Mark Hanrahan',
 ' CBRE',
 'Athena Chan',
 ' Tashny Sukumaran',
 ' Dewey Sim',
 'ANKITA RAO',
 ' Brendan Clift',
 ' Agence France-Pressse',
 ' Tomiris Urstembayeva',
 ' Agence France Presse in Bangkok',
 ' Martin Campion',
 'Jitsiree Thongnoi',
 ' Eric Brattberg',
 ' William Zheng',
 ' Cathy Zhang',
 'Ng Kang-chung',
 'Meng Jing',
 ' Laura He',
 ' STEVE GALLAGHER',
 ' STAFF',
 ' Minnie Chan',
 ' Eddie Lee',
 ' Agence France Presse in Dandong',
 ' ELLIS LIANG',
 ' Tom Fawthrop',
 ' AGENCY',
 ' Laura Warne',
 ' The New York Times in Mexico City',
 'ANGELA',
 ' Alan Yu',
 ' JING YANG',
 ' JOLIE HO NATALIE WAI',
 'Hedy Bok',
 ' Austin Chiu',
 ' Keegan Elmer',
 ' ANN YIP',
 ' An excerpt',
 ' Dennis Wong',
 'JULIE CHU',
 ' DENNIS',
 'Zen Soo',
 'Alex Millson',
 ' CLIFFOD LO',
 ' Josh Horwitz',
 'Christopher Johnson',
 ' Agence France Presse in New York',
 ' Agence France Presse in Beiru',
 ' Richard Pretorius',
 'Jane Cai',
 ' Agence France Presse in Caracas',
 ' Colleen Lee',
 ' SW',
 ' Sarah Dai',
 ' Harminder Singh',
 'S HIRLEY ZHAO',
 'Coco Liu',
 ' Douglas Parkes',
 'WESLEY CHAN',
 ' Christy Leung',
 ' Adam Cathcart',
 'Don Weinland',
 'Martin Choi',
 'Pranay Sharma',
 'Florida',
 ' SCMP Reporter',
 ' Agence France-Press in Caracas',
 ' VRIOUS',
 'Cherie Chan',
 ' HAN SHI',
 'Tracy Zhang',
 ' Peggy Yuan`',
 'Raymond Yeung',
 ' Agence France Press in Johannesburg',
 ' LEE CHACK-FAN',
 'Liu Yi',
 'Cheryl Heng',
 'CHIM SAU-WAI',
 ' MARCEL KOO',
 ' MICHAEL DE WAAL-MONTGOMERY',
 ' Marco Polo Hotels',
 ' Pearl Lee',
 ' Anita Shum',
 ' CLIFFORD',
 ' Zeyi Yang',
 ' Alan Morison',
 ' Echo Hui',
 ' Mikhail Perfilov',
 ' Finbarr Bermingham',
 ' Kristine Kwok',
 ' Anna Cummins',
 'Sijia Jiang',
 ' Simon Young',
 ' Ariel Conant',
 ' Alvin Lum',
 ' NG KC',
 ' Cynthia Wu',
 ' Daniel Ren',
 ' ALLEN AUYEUNG',
 ' ALEXANDER STIRN',
 'Josephine Ma',
 'Eric Ng',
 ' Doris Lam',
 ' Samuel Chan',
 'CAROL CHEUNG',
 'NG KANG=CHUNG',
 'Kristie Wong',
 ' Thomas Bird',
 'AUSTIN CHUI',
 ' Ankit Panda',
 ' DAVID MALLINSON',
 'Robert Delaney',
 ' Richard Lord',
 ' Peter Morgan',
 ' SALLY WANG',
 'Johnny Tam',
 'Bennett Murray',
 ' Compiled by Francine Chen',
 'FANNY W.Y. FUNG',
 'Victoria Ruan',
 'Jennifer Colegate',
 ' Felix Wong',
 'CHUNG HOANG',
 ' PINGHUI',
 ' The New York Times in Beirut',
 ' Wang Feng',
 ' Thomas CW Chan',
 'Danny Mok',
 ' Kinling Lo',
 ' LO  WEI',
 ' Zen Soo',
 ' Di',
 ' Agence France Press in Perth',
 ' JOSHUA BUT',
 'Enid Tsui',
 ' Jeffie Lam',
 'Jacqueline Feldscher',
 ' WESLEY CHAN',
 ' Rajeev Ranjan Chaturvedy',
 ' Peggy Yuan',
 'NAILL FRASER',
 ' Zhang Lin',
 ' SCMP',
 'Mantai Chow',
 ' Cheung Chi Fai',
 ' CITY BRIEFS',
 ' Emily Brill',
 ' Lai Ying Kit',
 ' ANNE RENZENBRINK',
 'Linda Lew',
 'Laurie Chen',
 'Adam Martin',
 ' Michael Beltran',
 ' Jacqueline Woo',
 'Castiel Ho',
 ' Haroon Janjua',
 'James Porteous',
 'Edmund Lee',
 ' Holly Chik',
 " LYNNE O'DONNELL",
 'Violet Law',
 ' Rodrigo Zeidan',
 ' Jack Lau',
 'Lawrence Chung',
 ' Veronica Lin',
 ' Robin Lynam',
 'Lana Lam',
 'Vivienne Chow',
 ' AND BLOOMBERG',
 ' The New York Times in Ain Leuh',
 ' Phoenix Kwong',
 ' Lai Ying-ki',
 ' Charles Dunst',
 ' Kerry Brown',
 ' RAYMOMD LI',
 ' Korea Times',
 'Amy Chew',
 ' Qin Chen',
 ' Karen Lee',
 'JENNY YU',
 'ANTONIO TALIA',
 ' Eduardo Baptista',
 ' Snow Xia',
 ' Kunal Purohit',
 ' ALEX BOOKBINDER',
 ' Stephy Shi Yuhan',
 ' VICTORIAL RUAN',
 'JOYCE',
 'Yujing Liu',
 'Masha Borak',
 ' Liu Yi',
 'Jeffie Lam',
 ' Linda Lew',
 ...]

# Tag Frequencies

In [82]:
links_text = ' '.join(list(df.Link))
links_text_clean1 = links_text.replace("https://www.scmp.com/news", " ")

In [83]:
tags = set(re.findall(r'  (.*?)article', links_text_clean1))

In [84]:
unique_tags = []
tags_list = list(tags)[1:]
for tag in tags_list:
    u = re.findall(r'/(.*?)/', tag)
    unique_tags.extend(u)

In [85]:
'''
 #contain_southEastAsia
 '/south-east-asia/',
 '/southeast-asia/',
 
 #contain_diplomacy
 '/diplomacy-defence/',
 '/diplomacy/',
 
 #contain_politics
 '/policies-politics/',
 '/poliitics/',
 '/politics-policy/',
 '/politics/',
 
 #contain_economy
 '/economy/',
 '/china-economy/',
  /hong-kong-economy/,
  
  #contain_education
 '/education-community/',
 '/education/',
 
  #contain_lawCrime
  '/hong-kong-law-and-crime/',
  '/law-and-crime/',
  '/law-crime/',
 
 #contain_community
  '/community/',
  '/education-community/',
  
 #contain_environment
 '/environment/',
 '/health-environment/',
 
 #contain_society
 '/social-issues/',
 '/society/',
 
 
 #contain_americas
 '/united-states-canada/',
 '/united-states/',
 '/americas/',
 '/us/'}
 
# 
 

'''
tags

{'/',
 '/asia/',
 '/asia/australasia/',
 '/asia/diplomacy/',
 '/asia/east-asia/',
 '/asia/south-asia/',
 '/asia/south-east-asia/',
 '/asia/southeast-asia/',
 '/china-digest/',
 '/china-insider/',
 '/china/',
 '/china/china-economy/',
 '/china/diplomacy-defence/',
 '/china/diplomacy/',
 '/china/economy/',
 '/china/military/',
 '/china/money-wealth/',
 '/china/policies-politics/',
 '/china/poliitics/',
 '/china/politics-policy/',
 '/china/politics/',
 '/china/science/',
 '/china/society/',
 '/hong-kong/',
 '/hong-kong/community/',
 '/hong-kong/economy/',
 '/hong-kong/education-community/',
 '/hong-kong/education/',
 '/hong-kong/environment/',
 '/hong-kong/health-environment/',
 '/hong-kong/hong-kong-economy/',
 '/hong-kong/hong-kong-law-and-crime/',
 '/hong-kong/law-and-crime/',
 '/hong-kong/law-crime/',
 '/hong-kong/media/',
 '/hong-kong/politics/',
 '/hong-kong/social-issues/',
 '/hong-kong/society/',
 '/hong-kong/transport/',
 '/world/',
 '/world/africa/',
 '/world/americas/',
 '/world/europe/',
 '/world/middle-east/',
 '/world/russia-central-asia/',
 '/world/united-states-canada/',
 '/world/united-states/',
 '/world/us/'}

In [86]:
unique_tags = ["/asia/", "/australasia/", "/east-asia/" ,"/military/"
 , "/money-wealth/" , "/science/", "/transport/", "/media/" , "/world/"
 , "/africa/", "/europe/","/middle-east/","/russia-central-asia/", "/south-asia/"]

tag_dict = {new_list: [] for new_list in unique_tags} 

for key in tag_dict:
    for link in df.Link:
        if key in link:
            tag_dict[key].append(1)
        else:
            tag_dict[key].append(0)
            
col_names = {'/asia/':'Asia', '/australasia/':'Australasia', '/east-asia/':'EastAsia',
      '/military/':'Military', '/money-wealth/':'MoneyWealth', '/science/':'Science',
      '/transport/':'Transport', '/media/':'Media', '/world/':'World',
      '/africa/':'Africa', '/europe/':'Europe', '/middle-east/':'MiddleEast',
     '/russia-central-asia/':'RussiaCentralAsia', '/south-asia/':'SouthAsia'}

tag_dict_list = dict((col_names[key], value) for (key, value) in tag_dict.items())

In [87]:
b = pd.concat({k: pd.Series(v) for k, v in tag_dict_list.items()}, axis=1)
b

,Asia,Australasia,EastAsia,Military,MoneyWealth,Science,Transport,Media,World,Africa,Europe,MiddleEast,RussiaCentralAsia,SouthAsia
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92246,0,0,0,0,0,0,0,0,0,0,0,0,0,0
92247,0,0,0,0,0,0,0,0,0,0,0,0,0,0
92248,0,0,0,0,0,0,0,0,0,0,0,0,0,0
92249,0,0,0,0,0,0,0,0,0,0,0,0,0,0
92250,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [88]:
#just got the tags manually
contain_china = []
contain_hk = []
contain_southEastAsia = []
contain_diplomacy = []
contain_politics = []
contain_economy = []
contain_education = []
contain_lawCrime = []
contain_community = []
contain_environment = []
contain_society = []
contain_americas = []

for link in df.Link:
    #contain_china
    if '/china/' in link or '/china-digest/' in link or '/china-insider/' in link :
        contain_china.append(1)
    else:
        contain_china.append(0)
    
    #contain_hk
    if '/hong-kong/' in link:
        contain_hk.append(1)
    else:
        contain_hk.append(0)

    #contain_southEastAsia
    if '/south-east-asia/' in link or '/southeast-asia/' in link:
        contain_southEastAsia.append(1)
    else:
        contain_southEastAsia.append(0)
        
    #contain_diplomacy 
    if '/diplomacy-defence/' in link or '/diplomacy/' in link:
        contain_diplomacy.append(1)
    else:
        contain_diplomacy.append(0)

    #contain_politics 
    if '/policies-politics/' in link or '/politics/' in link or '/politics-policy/' in link or '/poliitics/' in link:
        contain_politics.append(1)
    else:
        contain_politics.append(0)
        
    #contain_economy 
    if '/economy/' in link or '/china-economy/' in link or '/hong-kong-economy/' in link:
        contain_economy.append(1)
    else:
        contain_economy.append(0)

    #contain_education
    if '/education-community/' in link or '/education/' in link:
        contain_education.append(1)
    else:
        contain_education.append(0)
        
    #contain_lawCrime 
    if '/hong-kong-law-and-crime/' in link or '/law-and-crime/' in link or '/law-crime/' in link :
        contain_lawCrime.append(1)
    else:
        contain_lawCrime.append(0)
        
    #contain_community 
    if '/community/' in link or '/education-community/' in link:
        contain_community.append(1)
    else:
        contain_community.append(0)
        
    #contain_environment 
    if '/environment/' in link or '/health-environment/' in link:
        contain_environment.append(1)
    else:
        contain_environment.append(0)
        
    #contain_society 
    if '/social-issues/' in link or '/society/' in link:
        contain_society.append(1)
    else:
        contain_society.append(0)
        
    #contain_americas 
    if '/united-states-canada/' in link or '/americas/' in link or '/united-states/' in link or '/us/' in link:
        contain_americas.append(1)
    else:
        contain_americas.append(0)

In [89]:
china_df['China'] = contain_china

df['China'] = contain_china
df['HongKong'] = contain_hk
df['SouthEastAsia'] = contain_southEastAsia
df['Diplomacy'] = contain_diplomacy
df['Politics'] = contain_politics
df['Economy'] = contain_economy
df['Education'] = contain_education
df['LawAndCrime'] = contain_lawCrime
df['Community'] = contain_community
df['Environment'] = contain_environment
df['Society'] = contain_society
df['Americas'] = contain_americas

df = pd.concat([df, b], axis=1, sort=False)

In [90]:
df = df.drop(columns = ["Title","Author","Summary", "Topic", "Link"])
df

,Date,China,HongKong,SouthEastAsia,Diplomacy,Politics,Economy,Education,LawAndCrime,Community,...,MoneyWealth,Science,Transport,Media,World,Africa,Europe,MiddleEast,RussiaCentralAsia,SouthAsia
0,2012-08-12 13:59:00+00:00,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2012-08-12 14:17:00+00:00,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2012-08-12 15:57:00+00:00,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2012-08-12 16:59:00+00:00,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2012-08-12 23:13:00+00:00,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92246,2020-11-14 15:28:00+00:00,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
92247,2020-11-14 15:30:00+00:00,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
92248,2020-11-14 15:30:00+00:00,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
92249,2020-11-14 15:47:00+00:00,0,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
92250,2020-11-14 16:03:00+00:00,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [91]:
tag_df = df.groupby([df.Date.dt.year, df.Date.dt.month]).agg(['sum'])
tag_df.columns = tag_df.columns.droplevel(1)

In [92]:
new_index = []
for i in tag_df.index.to_flat_index():
    i = str(i)[1:-1]
    new_index.append(i)
tag_df.index = new_index
tag_df

,China,HongKong,SouthEastAsia,Diplomacy,Politics,Economy,Education,LawAndCrime,Community,Environment,...,MoneyWealth,Science,Transport,Media,World,Africa,Europe,MiddleEast,RussiaCentralAsia,SouthAsia
"2012, 8",82,327,0,0,0,0,0,0,0,0,...,0,0,0,0,7,0,0,0,0,0
"2012, 9",155,527,0,0,0,0,0,0,0,0,...,0,0,0,0,25,0,0,0,0,0
"2012, 10",223,539,0,0,0,0,0,0,0,0,...,0,0,0,0,55,0,0,0,0,0
"2012, 11",7,29,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
"2012, 12",252,523,0,0,0,0,0,0,0,0,...,0,0,0,0,45,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"2020, 7",361,481,13,162,184,35,27,104,0,88,...,0,38,13,0,57,4,10,1,1,2
"2020, 8",343,548,7,147,120,66,63,131,0,127,...,1,35,15,0,38,2,11,2,0,4
"2020, 9",349,496,20,166,119,48,43,146,0,100,...,1,39,19,0,30,0,9,2,2,1
"2020, 10",399,445,13,174,142,52,28,114,0,75,...,0,32,30,0,40,0,14,1,2,0
"2020, 11",161,212,6,82,76,14,19,63,0,35,...,0,10,7,0,16,0,6,0,0,2

In [93]:
tag_df.T.to_csv("../../../Capstone_Idyll/data/tagged_observable.csv")

# Get Ratio

In [94]:
ratio_df = df.groupby([df.Date.dt.year]).agg(['sum'])
ratio_df.columns = ratio_df.columns.droplevel(1)

ratio = ratio_df['China'] /  ratio_df['HongKong']

In [95]:
ratio_df = pd.DataFrame.from_dict(dict(ratio), orient='index',
                       columns=[ 'Ratio'])

ratio_df.reset_index(inplace=True)
ratio_df = ratio_df.rename(columns={'index':'Date'})
ratio_df

   Date     Ratio
0  2012  0.369666
1  2013  0.581380
2  2014  0.578819
3  2015  0.457020
4  2016  0.525302
5  2017  0.736247
6  2018  0.687087
7  2019  0.719660
8  2020  0.765895

In [96]:
ratio_df.to_csv("../../../Capstone_Idyll/data/ratio_data.csv", index=False)

# Get China Articles

In [334]:
china_df = china_df[china_df.China != 0]
china_df = china_df.drop(columns = ["Topic", "China", "Summary"])

,Title,Author,Link,Date
10,China's team praised as London Olympics close,Chan Kin Wa,https://www.scmp.com/news/china/article/1008790/chinas-team-praised-london-olympics-close,2012-08-13 00:57:00+00:00
12,Billionaire Chen Guangbiao promotes plan for bottled air by smashing e-bicycles,Laura Zhou,https://www.scmp.com/news/china/article/1008791/billionaire-chen-guangbiao-promotes-plan-bottled-air-smashing-e-bicycles,2012-08-13 01:00:00+00:00
13,Taiwanese legislators threaten to block cross-strait investment protection pact,Lawrence Chung,https://www.scmp.com/news/china/article/1008777/taiwanese-legislators-threaten-block-cross-strait-investment-protection,2012-08-13 01:04:00+00:00
18,Outspoken playwright Sha urges Hongkongers to keep democratic voice strong,LOUISE HO,https://www.scmp.com/news/china/article/1008774/outspoken-playwright-sha-urges-hongkongers-keep-democratic-voice-strong,2012-08-13 02:55:00+00:00
19,Army joins police in hunt for killer in Chongqing,Mimi Lau,https://www.scmp.com/news/china/article/1008779/army-joins-police-hunt-killer-chongqing,2012-08-13 04:12:00+00:00
...,...,...,...,...
92240,TikTok gets 15-day extension as US sale deadline is pushed to November 27,Jodi Xu Klein,https://www.scmp.com/news/china/article/3109834/tiktok-gets-15-day-extension-us-sale-deadline-pushed-november-27,2020-11-14 14:49:00+00:00
92241,Does Taiwan’s caution on ‘military training’ show US support has limits?,Lawrence Chung,https://www.scmp.com/news/china/military/article/3109789/does-taiwans-caution-military-training-show-us-support-has,2020-11-14 14:49:00+00:00
92243,South China Sea: will Joe Biden take a more cautious approach in the disputed waters?,Laura Zhou,https://www.scmp.com/news/china/diplomacy/article/3109773/south-china-sea-will-joe-biden-take-more-cautious-approach,2020-11-14 15:21:00+00:00
92245,A harder US line? Potential Pentagon chief floated idea to sink China fleet in 72 hours,Liu Zhen,https://www.scmp.com/news/china/military/article/3109852/harder-us-line-potential-pentagon-chief-floated-idea-sink-china,2020-11-14 15:21:00+00:00
92248,Pope Francis said to be in final stage of selecting new Hong Kong bishop,Mimi Lau,https://www.scmp.com/news/china/diplomacy/article/3109825/pope-francis-said-be-final-stage-selecting-new-hong-kong,2020-11-14 15:30:00+00:00

In [100]:
china_df.to_csv("../../../Capstone_Idyll/data/china_colab.csv",index = False)

# China Sentiment

In [122]:
colab_df = pd.read_csv('../Pickles/china_df.csv')
colab_df.Date = pd.to_datetime(colab_df.Date)
colab_df = colab_df[~colab_df.Title.str.contains("China Digest")]
colab_df.head(5)

,Unnamed: 0,Link,Title,Author,Date,Prediction,Negative_Score,Positive_Score
0,0,https://www.scmp.com/news/china/article/1008790/chinas-team-praised-london-olympics-close,China's team praised as London Olympics close,Chan Kin Wa,2012-08-13 00:57:00+00:00,1,0.001294,0.998706
1,1,https://www.scmp.com/news/china/article/1008791/billionaire-chen-guangbiao-promotes-plan-bottled-air-smashing-e-bicycles,Billionaire Chen Guangbiao promotes plan for bottled air by smashing e-bicycles,Laura Zhou,2012-08-13 01:00:00+00:00,1,0.394052,0.605948
2,2,https://www.scmp.com/news/china/article/1008777/taiwanese-legislators-threaten-block-cross-strait-investment-protection,Taiwanese legislators threaten to block cross-strait investment protection pact,Lawrence Chung,2012-08-13 01:04:00+00:00,0,0.858571,0.141430
3,3,https://www.scmp.com/news/china/article/1008774/outspoken-playwright-sha-urges-hongkongers-keep-democratic-voice-strong,Outspoken playwright Sha urges Hongkongers to keep democratic voice strong,LOUISE HO,2012-08-13 02:55:00+00:00,1,0.000439,0.999561
4,4,https://www.scmp.com/news/china/article/1008779/army-joins-police-hunt-killer-chongqing,Army joins police in hunt for killer in Chongqing,Mimi Lau,2012-08-13 04:12:00+00:00,1,0.145623,0.854377

In [123]:
colab_df = colab_df.drop(columns = ["Unnamed: 0", "Title",'Author',"Link", "Negative_Score","Prediction"])
colab_df = colab_df.groupby([colab_df.Date.dt.year, colab_df.Date.dt.month]).agg(['median'])

new_index = []
for i in colab_df.index.to_flat_index():
    i = str(i)[1:-1]
    new_index.append(i)
colab_df.index = new_index
colab_df.reset_index(inplace=True)
colab_df.columns = colab_df.columns.droplevel(1)

colab_df= colab_df.rename(columns={'index':'Date'})

In [124]:
colab_df.to_csv("../../../Capstone_Idyll/data/china_sentiment_data.csv", index=False)

# Sentiment + Bias Dataset

In [125]:
colab_df

        Date  Positive_Score
0   2012, 8   0.778351
1   2012, 9   0.478372
2   2012, 10  0.944698
3   2012, 11  0.504763
4   2012, 12  0.574599
..       ...       ...
95  2020, 7   0.548438
96  2020, 8   0.614219
97  2020, 9   0.530829
98  2020, 10  0.576001
99  2020, 11  0.890447

[100 rows x 2 columns]